"""add score and total_questions to daily_question_completions

Revision ID: 1083271479c5
Revises: b53d97796f9a
Create Date: 2026-02-14 13:14:37.094946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1083271479c5'
down_revision: Union[str, Sequence[str], None] = 'b53d97796f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assignments_schedule_id_fkey'), 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'schedule_id')
    op.add_column('daily_question_completions', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('daily_question_completions', sa.Column('total_questions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_question_completions', 'total_questions')
    op.drop_column('daily_question_completions', 'score')
    op.add_column('assignments', sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('assignments_schedule_id_fkey'), 'assignments', 'lesson_schedules', ['schedule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
