"""add_grading_fields_to_quiz_attempt

Revision ID: 109c36fa19fa
Revises: 783d1f7224a3
Create Date: 2025-12-06 18:15:08.144847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109c36fa19fa'
down_revision: Union[str, Sequence[str], None] = '783d1f7224a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('is_graded', sa.Boolean(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('feedback', sa.Text(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('graded_by', sa.Integer(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('graded_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'quiz_attempts', 'users', ['graded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_column('quiz_attempts', 'graded_at')
    op.drop_column('quiz_attempts', 'graded_by')
    op.drop_column('quiz_attempts', 'feedback')
    op.drop_column('quiz_attempts', 'is_graded')
    # ### end Alembic commands ###
