"""Add lesson_id to Event

Revision ID: 120114765544
Revises: 4dfefac419bc
Create Date: 2026-01-15 17:57:28.692326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120114765544'
down_revision: Union[str, Sequence[str], None] = '4dfefac419bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'lesson_id')
    # ### end Alembic commands ###
