"""add quiz draft support fields

Revision ID: 154214d8c0f4
Revises: d7722171a482
Create Date: 2026-01-03 16:30:41.812743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '154214d8c0f4'
down_revision: Union[str, Sequence[str], None] = 'd7722171a482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # Add is_draft with server_default first, then make it non-nullable
    op.add_column('quiz_attempts', sa.Column('is_draft', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('quiz_attempts', sa.Column('current_question_index', sa.Integer(), nullable=True))
    op.alter_column('quiz_attempts', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_attempts', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('quiz_attempts', 'current_question_index')
    op.drop_column('quiz_attempts', 'is_draft')
    op.drop_column('quiz_attempts', 'updated_at')
    # ### end Alembic commands ###
