"""add_group_students_association_table

Revision ID: 237a9365b3ec
Revises: 70a1e23b83a0
Create Date: 2025-08-17 12:41:47.016309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237a9365b3ec'
down_revision: Union[str, Sequence[str], None] = '70a1e23b83a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_group_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_group_id_fkey'), 'users', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
