"""add_teacher_id_to_events

Revision ID: 24e09c407c2f
Revises: 120114765544
Create Date: 2026-01-15 18:24:23.771688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e09c407c2f'
down_revision: Union[str, Sequence[str], None] = '120114765544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'teacher_id')
    # ### end Alembic commands ###
