"""remove_old_lesson_columns

Revision ID: 4afa85b40fba
Revises: 49f7555e8acb
Create Date: 2025-08-22 11:04:52.435155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afa85b40fba'
down_revision: Union[str, Sequence[str], None] = '49f7555e8acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'content_text')
    op.drop_column('lessons', 'content_type')
    op.drop_column('lessons', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('content_text', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
