"""add_event_id_to_assignments

Revision ID: 61fd2b69a0a3
Revises: df96114ea1e1
Create Date: 2026-01-25 23:59:04.197921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61fd2b69a0a3'
down_revision: Union[str, Sequence[str], None] = 'df96114ea1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_assignment_submission_graded'), table_name='assignment_submissions')
    op.add_column('assignments', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignments', 'events', ['event_id'], ['id'], ondelete='SET NULL')
    op.alter_column('attendances', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'present'::character varying"))
    op.alter_column('attendances', 'score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('attendances', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_course_analytics_cache_course_id'), table_name='course_analytics_cache')
    op.drop_index(op.f('idx_enrollment_user_active'), table_name='enrollments', postgresql_where='(is_active = true)')
    op.alter_column('group_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('group_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lesson_schedules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_step_progress_status_completed'), table_name='step_progress', postgresql_where="((status)::text = 'completed'::text)")
    op.drop_index(op.f('idx_step_progress_user_course'), table_name='step_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_step_progress_user_course'), 'step_progress', ['user_id', 'course_id'], unique=False)
    op.create_index(op.f('idx_step_progress_status_completed'), 'step_progress', ['status'], unique=False, postgresql_where="((status)::text = 'completed'::text)")
    op.alter_column('lesson_schedules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('group_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('group_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('idx_enrollment_user_active'), 'enrollments', ['user_id', 'is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('ix_course_analytics_cache_course_id'), 'course_analytics_cache', ['course_id'], unique=True)
    op.alter_column('attendances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendances', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendances', 'score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('attendances', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'present'::character varying"))
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'event_id')
    op.create_index(op.f('idx_assignment_submission_graded'), 'assignment_submissions', ['is_graded'], unique=False)
    # ### end Alembic commands ###
