"""add_skill_assessment_fields_to_assignment_zero

Revision ID: 65172b7f737d
Revises: b574bc6341a8
Create Date: 2026-01-10 17:06:08.647548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65172b7f737d'
down_revision: Union[str, Sequence[str], None] = 'b574bc6341a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_zero_submissions', sa.Column('grammar_punctuation', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('grammar_noun_clauses', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('grammar_relative_clauses', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('grammar_verb_forms', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('grammar_comparisons', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('grammar_transitions', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('grammar_synthesis', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('reading_word_in_context', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('reading_text_structure', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('reading_cross_text', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('reading_central_ideas', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('reading_inferences', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('passages_literary', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('passages_social_science', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('passages_humanities', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('passages_science', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('passages_poetry', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('math_topics', sa.JSON(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('additional_comments', sa.Text(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('is_draft', sa.Boolean(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('last_saved_step', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_zero_submissions', 'last_saved_step')
    op.drop_column('assignment_zero_submissions', 'is_draft')
    op.drop_column('assignment_zero_submissions', 'additional_comments')
    op.drop_column('assignment_zero_submissions', 'math_topics')
    op.drop_column('assignment_zero_submissions', 'passages_poetry')
    op.drop_column('assignment_zero_submissions', 'passages_science')
    op.drop_column('assignment_zero_submissions', 'passages_humanities')
    op.drop_column('assignment_zero_submissions', 'passages_social_science')
    op.drop_column('assignment_zero_submissions', 'passages_literary')
    op.drop_column('assignment_zero_submissions', 'reading_inferences')
    op.drop_column('assignment_zero_submissions', 'reading_central_ideas')
    op.drop_column('assignment_zero_submissions', 'reading_cross_text')
    op.drop_column('assignment_zero_submissions', 'reading_text_structure')
    op.drop_column('assignment_zero_submissions', 'reading_word_in_context')
    op.drop_column('assignment_zero_submissions', 'grammar_synthesis')
    op.drop_column('assignment_zero_submissions', 'grammar_transitions')
    op.drop_column('assignment_zero_submissions', 'grammar_comparisons')
    op.drop_column('assignment_zero_submissions', 'grammar_verb_forms')
    op.drop_column('assignment_zero_submissions', 'grammar_relative_clauses')
    op.drop_column('assignment_zero_submissions', 'grammar_noun_clauses')
    op.drop_column('assignment_zero_submissions', 'grammar_punctuation')
    # ### end Alembic commands ###
