"""add is_hidden to assignment_submissions

Revision ID: 693ab3782567
Revises: fee60e07d849
Create Date: 2025-12-04 19:17:17.992663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693ab3782567'
down_revision: Union[str, Sequence[str], None] = 'fee60e07d849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_submissions', 'is_hidden')
    # ### end Alembic commands ###
