"""add_curator_id_to_groups

Revision ID: 70a1e23b83a0
Revises: 9850e93f5ef5
Create Date: 2025-08-17 12:33:26.507586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a1e23b83a0'
down_revision: Union[str, Sequence[str], None] = '9850e93f5ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Guarded drops in case indexes were never created in this environment
    from sqlalchemy import text
    bind = op.get_bind()
    guard_drop_statements = [
        "DROP INDEX IF EXISTS idx_courses_is_active",
        "DROP INDEX IF EXISTS idx_courses_teacher_id",
        "DROP INDEX IF EXISTS idx_lessons_content_type",
        "DROP INDEX IF EXISTS idx_lessons_module_id",
        "DROP INDEX IF EXISTS idx_lessons_module_order",
        "DROP INDEX IF EXISTS idx_lessons_order_index",
        "DROP INDEX IF EXISTS idx_modules_course_id",
        "DROP INDEX IF EXISTS idx_modules_course_order",
        "DROP INDEX IF EXISTS idx_modules_order_index",
    ]
    for stmt in guard_drop_statements:
        try:
            bind.execute(text(stmt))
        except Exception:
            # Ignore if index doesn't exist or name differs; this is best-effort clean-up
            pass

    # Add column and FK only if not exists
    bind.execute(text("ALTER TABLE groups ADD COLUMN IF NOT EXISTS curator_id INTEGER"))
    bind.execute(text(
        """
        DO $$
        BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.table_constraints tc
            WHERE tc.constraint_name = 'fk_groups_curator_id_users'
              AND tc.table_name = 'groups'
              AND tc.constraint_type = 'FOREIGN KEY'
        ) THEN
            ALTER TABLE groups
            ADD CONSTRAINT fk_groups_curator_id_users
            FOREIGN KEY (curator_id) REFERENCES users(id);
        END IF;
        END$$;
        """
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_modules_order_index'), 'modules', ['order_index'], unique=False)
    op.create_index(op.f('idx_modules_course_order'), 'modules', ['course_id', 'order_index'], unique=False)
    op.create_index(op.f('idx_modules_course_id'), 'modules', ['course_id'], unique=False)
    op.create_index(op.f('idx_lessons_order_index'), 'lessons', ['order_index'], unique=False)
    op.create_index(op.f('idx_lessons_module_order'), 'lessons', ['module_id', 'order_index'], unique=False)
    op.create_index(op.f('idx_lessons_module_id'), 'lessons', ['module_id'], unique=False)
    op.create_index(op.f('idx_lessons_content_type'), 'lessons', ['content_type'], unique=False)
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'curator_id')
    op.create_index(op.f('idx_courses_teacher_id'), 'courses', ['teacher_id'], unique=False)
    op.create_index(op.f('idx_courses_is_active'), 'courses', ['is_active'], unique=False)
    # ### end Alembic commands ###
