"""add_curator_id_to_groups

Revision ID: 70a1e23b83a0
Revises: 9850e93f5ef5
Create Date: 2025-08-17 12:33:26.507586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a1e23b83a0'
down_revision: Union[str, Sequence[str], None] = '9850e93f5ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_courses_is_active'), table_name='courses')
    op.drop_index(op.f('idx_courses_teacher_id'), table_name='courses')
    op.add_column('groups', sa.Column('curator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'users', ['curator_id'], ['id'])
    op.drop_index(op.f('idx_lessons_content_type'), table_name='lessons')
    op.drop_index(op.f('idx_lessons_module_id'), table_name='lessons')
    op.drop_index(op.f('idx_lessons_module_order'), table_name='lessons')
    op.drop_index(op.f('idx_lessons_order_index'), table_name='lessons')
    op.drop_index(op.f('idx_modules_course_id'), table_name='modules')
    op.drop_index(op.f('idx_modules_course_order'), table_name='modules')
    op.drop_index(op.f('idx_modules_order_index'), table_name='modules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_modules_order_index'), 'modules', ['order_index'], unique=False)
    op.create_index(op.f('idx_modules_course_order'), 'modules', ['course_id', 'order_index'], unique=False)
    op.create_index(op.f('idx_modules_course_id'), 'modules', ['course_id'], unique=False)
    op.create_index(op.f('idx_lessons_order_index'), 'lessons', ['order_index'], unique=False)
    op.create_index(op.f('idx_lessons_module_order'), 'lessons', ['module_id', 'order_index'], unique=False)
    op.create_index(op.f('idx_lessons_module_id'), 'lessons', ['module_id'], unique=False)
    op.create_index(op.f('idx_lessons_content_type'), 'lessons', ['content_type'], unique=False)
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'curator_id')
    op.create_index(op.f('idx_courses_teacher_id'), 'courses', ['teacher_id'], unique=False)
    op.create_index(op.f('idx_courses_is_active'), 'courses', ['is_active'], unique=False)
    # ### end Alembic commands ###
