"""add_is_initially_unlocked_to_lessons

Revision ID: 75469c92bb2c
Revises: 2c3472d9356a
Create Date: 2026-01-14 10:42:51.240496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75469c92bb2c'
down_revision: Union[str, Sequence[str], None] = '2c3472d9356a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('is_initially_unlocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'is_initially_unlocked')
    # ### end Alembic commands ###
