"""add_suggested_answer_to_question_error_reports

Revision ID: 7af5d2ac0f6a
Revises: af7c7cf905b6
Create Date: 2026-01-14 23:43:53.095424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af5d2ac0f6a'
down_revision: Union[str, Sequence[str], None] = 'af7c7cf905b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_error_reports', sa.Column('suggested_answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_error_reports', 'suggested_answer')
    # ### end Alembic commands ###
