"""add is_hidden to assignments

Revision ID: 82bef973b7f6
Revises: 693ab3782567
Create Date: 2025-12-04 19:46:29.947596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bef973b7f6'
down_revision: Union[str, Sequence[str], None] = '693ab3782567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'is_hidden')
    # ### end Alembic commands ###
