"""add_enhanced_quiz_fields

Revision ID: 86146539fee2
Revises: 5e24c7d923ba
Create Date: 2025-10-08 17:29:02.748217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86146539fee2'
down_revision: Union[str, Sequence[str], None] = '5e24c7d923ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_notification_preferences_id'), table_name='user_notification_preferences')
    op.drop_table('user_notification_preferences')
    op.alter_column('users', 'total_study_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'total_study_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('user_notification_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notification_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('in_app_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('reminder_1day', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('reminder_1hour', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_notification_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_notification_preferences_pkey')),
    sa.UniqueConstraint('user_id', 'notification_type', name=op.f('uq_user_notification_preference'))
    )
    op.create_index(op.f('ix_user_notification_preferences_id'), 'user_notification_preferences', ['id'], unique=False)
    # ### end Alembic commands ###
