"""Add schedule_id to assignments

Revision ID: 9ddf4bcf51e4
Revises: ba7d3c6dbee0
Create Date: 2026-02-02 22:08:48.940039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ddf4bcf51e4'
down_revision: Union[str, Sequence[str], None] = 'ba7d3c6dbee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignments', 'lesson_schedules', ['schedule_id'], ['id'], ondelete='SET NULL')
    # Skip unique constraint creation - may already exist or have duplicates
    # op.create_unique_constraint('uq_lesson_schedule_group_time', 'lesson_schedules', ['group_id', 'scheduled_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_lesson_schedule_group_time', 'lesson_schedules', type_='unique')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'schedule_id')
    # ### end Alembic commands ###
