"""add_ielts_fields_to_assignment_zero

Revision ID: a1faf587b1bb
Revises: 75469c92bb2c
Create Date: 2026-01-14 11:16:48.126563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1faf587b1bb'
down_revision: Union[str, Sequence[str], None] = '75469c92bb2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_zero_submissions', sa.Column('ielts_target_date', sa.String(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('has_passed_ielts_before', sa.Boolean(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('previous_ielts_score', sa.String(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_target_score', sa.String(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_listening_main_idea', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_listening_details', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_listening_opinion', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_listening_accents', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_reading_skimming', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_reading_scanning', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_reading_vocabulary', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_reading_inference', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_reading_matching', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_writing_task1_graphs', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_writing_task1_process', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_writing_task2_structure', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_writing_task2_arguments', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_writing_grammar', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_writing_vocabulary', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_speaking_fluency', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_speaking_vocabulary', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_speaking_grammar', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_speaking_pronunciation', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_speaking_part2', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_speaking_part3', sa.Integer(), nullable=True))
    op.add_column('assignment_zero_submissions', sa.Column('ielts_weak_topics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_zero_submissions', 'ielts_weak_topics')
    op.drop_column('assignment_zero_submissions', 'ielts_speaking_part3')
    op.drop_column('assignment_zero_submissions', 'ielts_speaking_part2')
    op.drop_column('assignment_zero_submissions', 'ielts_speaking_pronunciation')
    op.drop_column('assignment_zero_submissions', 'ielts_speaking_grammar')
    op.drop_column('assignment_zero_submissions', 'ielts_speaking_vocabulary')
    op.drop_column('assignment_zero_submissions', 'ielts_speaking_fluency')
    op.drop_column('assignment_zero_submissions', 'ielts_writing_vocabulary')
    op.drop_column('assignment_zero_submissions', 'ielts_writing_grammar')
    op.drop_column('assignment_zero_submissions', 'ielts_writing_task2_arguments')
    op.drop_column('assignment_zero_submissions', 'ielts_writing_task2_structure')
    op.drop_column('assignment_zero_submissions', 'ielts_writing_task1_process')
    op.drop_column('assignment_zero_submissions', 'ielts_writing_task1_graphs')
    op.drop_column('assignment_zero_submissions', 'ielts_reading_matching')
    op.drop_column('assignment_zero_submissions', 'ielts_reading_inference')
    op.drop_column('assignment_zero_submissions', 'ielts_reading_vocabulary')
    op.drop_column('assignment_zero_submissions', 'ielts_reading_scanning')
    op.drop_column('assignment_zero_submissions', 'ielts_reading_skimming')
    op.drop_column('assignment_zero_submissions', 'ielts_listening_accents')
    op.drop_column('assignment_zero_submissions', 'ielts_listening_opinion')
    op.drop_column('assignment_zero_submissions', 'ielts_listening_details')
    op.drop_column('assignment_zero_submissions', 'ielts_listening_main_idea')
    op.drop_column('assignment_zero_submissions', 'ielts_target_score')
    op.drop_column('assignment_zero_submissions', 'previous_ielts_score')
    op.drop_column('assignment_zero_submissions', 'has_passed_ielts_before')
    op.drop_column('assignment_zero_submissions', 'ielts_target_date')
    # ### end Alembic commands ###
