"""make_course_teacher_nullable

Revision ID: a3094110ab5e
Revises: 109c36fa19fa
Create Date: 2025-12-09 16:42:47.660009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3094110ab5e'
down_revision: Union[str, Sequence[str], None] = '109c36fa19fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('courses_teacher_id_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'users', ['teacher_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_teacher_id_fkey'), 'courses', 'users', ['teacher_id'], ['id'])
    op.alter_column('courses', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
