"""add_feedback_and_graded_by_to_assignment_submissions

Revision ID: b429e2c93464
Revises: ce1ef6bbb115
Create Date: 2025-08-25 16:29:25.907619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b429e2c93464'
down_revision: Union[str, Sequence[str], None] = 'ce1ef6bbb115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('feedback', sa.Text(), nullable=True))
    op.add_column('assignment_submissions', sa.Column('graded_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignment_submissions', 'users', ['graded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignment_submissions', type_='foreignkey')
    op.drop_column('assignment_submissions', 'graded_by')
    op.drop_column('assignment_submissions', 'feedback')
    # ### end Alembic commands ###
