"""add_lesson_number_to_assignments

Revision ID: b53d97796f9a
Revises: 1d03709cf2fa
Create Date: 2026-02-04 21:55:49.358495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53d97796f9a'
down_revision: Union[str, Sequence[str], None] = '1d03709cf2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('lesson_number', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_lesson_schedule_group_time', 'lesson_schedules', ['group_id', 'scheduled_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_lesson_schedule_group_time', 'lesson_schedules', type_='unique')
    op.drop_column('assignments', 'lesson_number')
    # ### end Alembic commands ###
