"""add assignment zero tables and fields

Revision ID: b574bc6341a8
Revises: 154214d8c0f4
Create Date: 2026-01-10 16:51:18.766182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b574bc6341a8'
down_revision: Union[str, Sequence[str], None] = '154214d8c0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assignment_submissions_assignment_id_fkey'), 'assignment_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'assignment_submissions', 'assignments', ['assignment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('assignments_group_id_fkey'), 'assignments', type_='foreignkey')
    op.drop_constraint(op.f('assignments_lesson_id_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'assignments', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('lesson_materials_lesson_id_fkey'), 'lesson_materials', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_materials', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('step_progress_lesson_id_fkey'), 'step_progress', type_='foreignkey')
    op.drop_constraint(op.f('step_progress_step_id_fkey'), 'step_progress', type_='foreignkey')
    op.drop_constraint(op.f('step_progress_course_id_fkey'), 'step_progress', type_='foreignkey')
    op.create_foreign_key(None, 'step_progress', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'step_progress', 'steps', ['step_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'step_progress', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('steps_lesson_id_fkey'), 'steps', type_='foreignkey')
    op.create_foreign_key(None, 'steps', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    
    # Add assignment_zero_completed with server_default first, then alter to remove default
    op.add_column('users', sa.Column('assignment_zero_completed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('assignment_zero_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'assignment_zero_completed_at')
    op.drop_column('users', 'assignment_zero_completed')
    op.drop_constraint(None, 'steps', type_='foreignkey')
    op.create_foreign_key(op.f('steps_lesson_id_fkey'), 'steps', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint(None, 'step_progress', type_='foreignkey')
    op.drop_constraint(None, 'step_progress', type_='foreignkey')
    op.drop_constraint(None, 'step_progress', type_='foreignkey')
    op.create_foreign_key(op.f('step_progress_course_id_fkey'), 'step_progress', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(op.f('step_progress_step_id_fkey'), 'step_progress', 'steps', ['step_id'], ['id'])
    op.create_foreign_key(op.f('step_progress_lesson_id_fkey'), 'step_progress', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint(None, 'lesson_materials', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_materials_lesson_id_fkey'), 'lesson_materials', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_lesson_id_fkey'), 'assignments', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(op.f('assignments_group_id_fkey'), 'assignments', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'assignment_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('assignment_submissions_assignment_id_fkey'), 'assignment_submissions', 'assignments', ['assignment_id'], ['id'])
    # ### end Alembic commands ###
