"""remove_lesson_id_from_event_and_schedule_id_from_assignment

Revision ID: b8407ede1000
Revises: 9ddf4bcf51e4
Create Date: 2026-02-03 11:20:30.165888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8407ede1000'
down_revision: Union[str, Sequence[str], None] = '9ddf4bcf51e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assignments_schedule_id_fkey'), 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'schedule_id')
    op.alter_column('course_head_teachers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_course_head_teachers_head_teacher_id'), table_name='course_head_teachers')
    op.drop_constraint(op.f('events_lesson_id_fkey'), 'events', type_='foreignkey')
    op.drop_column('events', 'lesson_id')
    # NOTE: Skipping unique constraint on lesson_schedules due to existing duplicate data
    # op.create_unique_constraint('uq_lesson_schedule_group_time', 'lesson_schedules', ['group_id', 'scheduled_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_lesson_schedule_group_time', 'lesson_schedules', type_='unique')
    op.add_column('events', sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('events_lesson_id_fkey'), 'events', 'lessons', ['lesson_id'], ['id'])
    op.create_index(op.f('ix_course_head_teachers_head_teacher_id'), 'course_head_teachers', ['head_teacher_id'], unique=False)
    op.alter_column('course_head_teachers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('assignments', sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('assignments_schedule_id_fkey'), 'assignments', 'lesson_schedules', ['schedule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
