"""add_late_submissions

Revision ID: ba7d3c6dbee0
Revises: 9fdd87126046
Create Date: 2026-01-31 01:15:51.282209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7d3c6dbee0'
down_revision: Union[str, Sequence[str], None] = '9fdd87126046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('is_late', sa.Boolean(), nullable=True))
    op.add_column('assignments', sa.Column('late_penalty_enabled', sa.Boolean(), nullable=True))
    op.add_column('assignments', sa.Column('late_penalty_multiplier', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'late_penalty_multiplier')
    op.drop_column('assignments', 'late_penalty_enabled')
    op.drop_column('assignment_submissions', 'is_late')
    # ### end Alembic commands ###
