"""Add AssignmentLinkedLesson table

Revision ID: bcc94a06e19a
Revises: e379ed8adbe0
Create Date: 2025-12-18 20:43:56.539615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc94a06e19a'
down_revision: Union[str, Sequence[str], None] = 'e379ed8adbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
