"""add_seen_by_student_to_submissions

Revision ID: cb6acafc124d
Revises: 82bef973b7f6
Create Date: 2025-12-05 21:10:10.180867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6acafc124d'
down_revision: Union[str, Sequence[str], None] = '82bef973b7f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('seen_by_student', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_submissions', 'seen_by_student')
    # ### end Alembic commands ###
