"""Add original_image_url to Step model

Revision ID: ce1ef6bbb115
Revises: 5199c7161408
Create Date: 2025-08-23 00:52:27.286157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1ef6bbb115'
down_revision: Union[str, Sequence[str], None] = '5199c7161408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('original_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'original_image_url')
    # ### end Alembic commands ###
