"""add_file_support_and_deadlines_to_assignments

Revision ID: d2c0eb95ab44
Revises: 237a9365b3ec
Create Date: 2025-08-17 21:00:09.283476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c0eb95ab44'
down_revision: Union[str, Sequence[str], None] = '237a9365b3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('file_url', sa.String(), nullable=True))
    op.add_column('assignment_submissions', sa.Column('submitted_file_name', sa.String(), nullable=True))
    op.add_column('assignments', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('assignments', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('assignments', sa.Column('file_url', sa.String(), nullable=True))
    op.add_column('assignments', sa.Column('allowed_file_types', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('assignments', sa.Column('max_file_size_mb', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignments', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'max_file_size_mb')
    op.drop_column('assignments', 'allowed_file_types')
    op.drop_column('assignments', 'file_url')
    op.drop_column('assignments', 'due_date')
    op.drop_column('assignments', 'group_id')
    op.drop_column('assignment_submissions', 'submitted_file_name')
    op.drop_column('assignment_submissions', 'file_url')
    # ### end Alembic commands ###
