"""add_file_support_and_deadlines_to_assignments

Revision ID: d2c0eb95ab44
Revises: 237a9365b3ec
Create Date: 2025-08-17 21:00:09.283476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c0eb95ab44'
down_revision: Union[str, Sequence[str], None] = '237a9365b3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Get existing columns
    submission_columns = [col['name'] for col in inspector.get_columns('assignment_submissions')]
    assignment_columns = [col['name'] for col in inspector.get_columns('assignments')]
    
    # Add columns only if they don't exist
    if 'file_url' not in submission_columns:
        op.add_column('assignment_submissions', sa.Column('file_url', sa.String(), nullable=True))
    
    if 'submitted_file_name' not in submission_columns:
        op.add_column('assignment_submissions', sa.Column('submitted_file_name', sa.String(), nullable=True))
    
    if 'group_id' not in assignment_columns:
        op.add_column('assignments', sa.Column('group_id', sa.Integer(), nullable=True))
    
    if 'due_date' not in assignment_columns:
        op.add_column('assignments', sa.Column('due_date', sa.DateTime(), nullable=True))
    
    if 'file_url' not in assignment_columns:
        op.add_column('assignments', sa.Column('file_url', sa.String(), nullable=True))
    
    if 'allowed_file_types' not in assignment_columns:
        op.add_column('assignments', sa.Column('allowed_file_types', sa.ARRAY(sa.String()), nullable=True))
    
    if 'max_file_size_mb' not in assignment_columns:
        op.add_column('assignments', sa.Column('max_file_size_mb', sa.Integer(), nullable=True))
    
    # Check if foreign key already exists
    fks = inspector.get_foreign_keys('assignments')
    has_group_fk = any(fk['referred_table'] == 'groups' and 'group_id' in fk['constrained_columns'] for fk in fks)
    
    if not has_group_fk and 'group_id' in assignment_columns:
        op.create_foreign_key(None, 'assignments', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'max_file_size_mb')
    op.drop_column('assignments', 'allowed_file_types')
    op.drop_column('assignments', 'file_url')
    op.drop_column('assignments', 'due_date')
    op.drop_column('assignments', 'group_id')
    op.drop_column('assignment_submissions', 'submitted_file_name')
    op.drop_column('assignment_submissions', 'file_url')
    # ### end Alembic commands ###
