"""add_lesson_columns_to_leaderboard

Revision ID: e379ed8adbe0
Revises: 9f008386b0d1
Create Date: 2025-12-16 21:24:02.064682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e379ed8adbe0'
down_revision: Union[str, Sequence[str], None] = '9f008386b0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaderboard_entries', sa.Column('lesson_1', sa.Float(), nullable=True))
    op.add_column('leaderboard_entries', sa.Column('lesson_2', sa.Float(), nullable=True))
    op.add_column('leaderboard_entries', sa.Column('lesson_3', sa.Float(), nullable=True))
    op.add_column('leaderboard_entries', sa.Column('lesson_4', sa.Float(), nullable=True))
    op.add_column('leaderboard_entries', sa.Column('lesson_5', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaderboard_entries', 'lesson_5')
    op.drop_column('leaderboard_entries', 'lesson_4')
    op.drop_column('leaderboard_entries', 'lesson_3')
    op.drop_column('leaderboard_entries', 'lesson_2')
    op.drop_column('leaderboard_entries', 'lesson_1')
    # ### end Alembic commands ###
