"""Add manual lesson unlocks

Revision ID: f79f2b52a182
Revises: c8f9a0b1d2e3
Create Date: 2026-01-20 15:45:39.999725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f79f2b52a182'
down_revision: Union[str, Sequence[str], None] = 'c8f9a0b1d2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_lesson_unlocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'group_id', name='uq_manual_unlock_group'),
    sa.UniqueConstraint('lesson_id', 'user_id', name='uq_manual_unlock_user')
    )
    op.create_index(op.f('ix_manual_lesson_unlocks_group_id'), 'manual_lesson_unlocks', ['group_id'], unique=False)
    op.create_index(op.f('ix_manual_lesson_unlocks_id'), 'manual_lesson_unlocks', ['id'], unique=False)
    op.create_index(op.f('ix_manual_lesson_unlocks_lesson_id'), 'manual_lesson_unlocks', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_manual_lesson_unlocks_user_id'), 'manual_lesson_unlocks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_lesson_unlocks_user_id'), table_name='manual_lesson_unlocks')
    op.drop_index(op.f('ix_manual_lesson_unlocks_lesson_id'), table_name='manual_lesson_unlocks')
    op.drop_index(op.f('ix_manual_lesson_unlocks_id'), table_name='manual_lesson_unlocks')
    op.drop_index(op.f('ix_manual_lesson_unlocks_group_id'), table_name='manual_lesson_unlocks')
    op.drop_table('manual_lesson_unlocks')
    # ### end Alembic commands ###
