"""Add manual lesson unlocks

Revision ID: f79f2b52a182
Revises: c8f9a0b1d2e3
Create Date: 2026-01-20 15:45:39.999725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f79f2b52a182'
down_revision: Union[str, Sequence[str], None] = 'c8f9a0b1d2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_lesson_unlocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'group_id', name='uq_manual_unlock_group'),
    sa.UniqueConstraint('lesson_id', 'user_id', name='uq_manual_unlock_user')
    )
    op.create_index(op.f('ix_manual_lesson_unlocks_group_id'), 'manual_lesson_unlocks', ['group_id'], unique=False)
    op.create_index(op.f('ix_manual_lesson_unlocks_id'), 'manual_lesson_unlocks', ['id'], unique=False)
    op.create_index(op.f('ix_manual_lesson_unlocks_lesson_id'), 'manual_lesson_unlocks', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_manual_lesson_unlocks_user_id'), 'manual_lesson_unlocks', ['user_id'], unique=False)
    op.drop_index(op.f('ix_external_service_cache_cache_key'), table_name='external_service_cache')
    op.drop_index(op.f('ix_external_service_cache_id'), table_name='external_service_cache')
    op.drop_index(op.f('ix_external_service_cache_service_name'), table_name='external_service_cache')
    op.drop_table('external_service_cache')
    op.drop_index(op.f('idx_assignment_submission_graded'), table_name='assignment_submissions')
    op.drop_index(op.f('ix_course_analytics_cache_course_id'), table_name='course_analytics_cache')
    op.drop_index(op.f('idx_enrollment_user_active'), table_name='enrollments', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_step_progress_status_completed'), table_name='step_progress', postgresql_where="((status)::text = 'completed'::text)")
    op.drop_index(op.f('idx_step_progress_user_course'), table_name='step_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_step_progress_user_course'), 'step_progress', ['user_id', 'course_id'], unique=False)
    op.create_index(op.f('idx_step_progress_status_completed'), 'step_progress', ['status'], unique=False, postgresql_where="((status)::text = 'completed'::text)")
    op.create_index(op.f('idx_enrollment_user_active'), 'enrollments', ['user_id', 'is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('ix_course_analytics_cache_course_id'), 'course_analytics_cache', ['course_id'], unique=True)
    op.create_index(op.f('idx_assignment_submission_graded'), 'assignment_submissions', ['is_graded'], unique=False)
    op.create_table('external_service_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cache_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('external_service_cache_pkey'))
    )
    op.create_index(op.f('ix_external_service_cache_service_name'), 'external_service_cache', ['service_name'], unique=False)
    op.create_index(op.f('ix_external_service_cache_id'), 'external_service_cache', ['id'], unique=False)
    op.create_index(op.f('ix_external_service_cache_cache_key'), 'external_service_cache', ['cache_key'], unique=True)
    op.drop_index(op.f('ix_manual_lesson_unlocks_user_id'), table_name='manual_lesson_unlocks')
    op.drop_index(op.f('ix_manual_lesson_unlocks_lesson_id'), table_name='manual_lesson_unlocks')
    op.drop_index(op.f('ix_manual_lesson_unlocks_id'), table_name='manual_lesson_unlocks')
    op.drop_index(op.f('ix_manual_lesson_unlocks_group_id'), table_name='manual_lesson_unlocks')
    op.drop_table('manual_lesson_unlocks')
    # ### end Alembic commands ###
