"""Make message created_at timezone aware

Revision ID: fee60e07d849
Revises: bc6c5c525916
Create Date: 2025-12-02 23:30:28.690186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fee60e07d849'
down_revision: Union[str, Sequence[str], None] = 'bc6c5c525916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assignment_submissions_assignment_id_fkey'), 'assignment_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'assignment_submissions', 'assignments', ['assignment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('assignments_group_id_fkey'), 'assignments', type_='foreignkey')
    op.drop_constraint(op.f('assignments_lesson_id_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'assignments', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('lesson_materials_lesson_id_fkey'), 'lesson_materials', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_materials', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('step_progress_step_id_fkey'), 'step_progress', type_='foreignkey')
    op.drop_constraint(op.f('step_progress_lesson_id_fkey'), 'step_progress', type_='foreignkey')
    op.drop_constraint(op.f('step_progress_course_id_fkey'), 'step_progress', type_='foreignkey')
    op.create_foreign_key(None, 'step_progress', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'step_progress', 'steps', ['step_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'step_progress', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('steps_lesson_id_fkey'), 'steps', type_='foreignkey')
    op.create_foreign_key(None, 'steps', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'steps', type_='foreignkey')
    op.create_foreign_key(op.f('steps_lesson_id_fkey'), 'steps', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint(None, 'step_progress', type_='foreignkey')
    op.drop_constraint(None, 'step_progress', type_='foreignkey')
    op.drop_constraint(None, 'step_progress', type_='foreignkey')
    op.create_foreign_key(op.f('step_progress_course_id_fkey'), 'step_progress', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(op.f('step_progress_lesson_id_fkey'), 'step_progress', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(op.f('step_progress_step_id_fkey'), 'step_progress', 'steps', ['step_id'], ['id'])
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'lesson_materials', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_materials_lesson_id_fkey'), 'lesson_materials', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_lesson_id_fkey'), 'assignments', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(op.f('assignments_group_id_fkey'), 'assignments', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'assignment_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('assignment_submissions_assignment_id_fkey'), 'assignment_submissions', 'assignments', ['assignment_id'], ['id'])
    # ### end Alembic commands ###
